#!/bin/env bash

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# history
## don't put duplicate lines in the history.
HISTCONTROL=ignoredups:ignorespace
## append to the history file, don't overwrite it
shopt -s histappend

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

PS1='\[\033[07;36m\] \$ \[\033[01;33m\]\w\[\033[00m\] '

# only for wsl
# shellcheck source=/dev/null
[[ -f ~/.bash_wsl ]] && . ~/.bash_wsl

# shellcheck source=/dev/null
[[ -f ~/.bash_aliases ]] && . ~/.bash_aliases

# add PATH env
if [[ -d ${HOME}/.local/bin/scripts ]]; then
    export PATH="${PATH}:${HOME}/.local/bin/scripts"
fi

# export xz/zstd OPTIONS
compression_thread_limit=$(($(nproc)-1))
export XZ_DEFAULTS="-7 -T ${compression_thread_limit}"
export ZSTD_CLEVEL=14
export ZSTD_NBTHREADS=${compression_thread_limit}
unset compression_thread_limit

# say todo
/bin/which say_todo.sh > /dev/null && say_todo.sh
