# for cmd color
alias ls='ls --color=auto'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
alias diff='diff --color=auto'

# for cmd options
alias l='ls -CF'
alias ll='ls -lhF'
alias la='ls -A'
alias du='du -h'
alias df='df -h'
alias sort='sort -h'
alias free='free -h'
alias gcc='gcc -Wall -pedantic -Wextra'
alias nm='nm -g'
alias radeontop="radeontop -b 03"
alias enca='enca -L zh_CN'
alias wdiff='wdiff -n'
alias scrcpy="scrcpy --power-off-on-close --turn-screen-off --stay-awake --no-clipboard-autosync &"
alias xsecurelock="env XSECURELOCK_AUTH_TIMEOUT=3 XSECURELOCK_PASSWORD_PROMPT=emoticon xsecurelock"
# alias xsecurelock="env XSECURELOCK_AUTH_TIMEOUT=3 XSECURELOCK_PASSWORD_PROMPT=time xsecurelock"

# for fast run
alias cl='clear'
alias pt='ping -c4 t.cn'
alias lg='tig status'
alias ff='fzf'
alias tz='tsocks trans -t zh'
alias qq='exit'
alias prime="DRI_PRIME=1"

# for swap cmd
alias rb='/bin/rm'
alias rm='trash.sh'
alias rl='trash.sh -l'
alias rr='trash.sh -r'
alias rc='trash.sh -c'
alias mount='mount | column -t'

_minicom()
    {
        log="${HOME}/.cache/minicom/$(date +%F_%T).log";
        /bin/minicom -C "${log}" -c on -D /dev/ttyS"$1" -b 115200;
        unset -f _minicom;
    };
alias minicom='_minicom'

# proxy
alias runproxy='export ALL_PROXY=socks5://127.0.0.1:7777'
alias unproxy='unset ALL_PROXY'
alias ipinfo='tsocks curl ipinfo.io' # or url as cip.cc

# rcm
alias lsrc='RCRC=${HOME}/.config/rcm/rcrc lsrc'
alias mkrc='RCRC=${HOME}/.config/rcm/rcrc mkrc'
alias rcdn='RCRC=${HOME}/.config/rcm/rcrc rcdn'
alias rcup='RCRC=${HOME}/.config/rcm/rcrc rcup'

# simple script
grepgbk() {
    env LANG=LC_ALL grep -rnP --color=auto "$(echo "$1" | iconv -f UTF8 -t GB18030)" "$2";
}

# arch update pacman mirrorlists
if [ -f /bin/pacman ];  then
    mirrorup() {
        mirror_urls="https://archlinux.org/mirrorlist/?country=CN&protocol=https&ip_version=4"
        echo "start update pacman mirrorlists"
        curl -s "${mirror_urls}" | grep edu | sed -e "s/^#Server/Server/" | rankmirrors -m 0.6 -v - | sudo tee /etc/pacman.d/mirrorlist > /dev/null
        echo "update pacman mirrorlists done"
        unset mirror_urls
    }
fi
