#!/bin/env bash

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# history
## don't put duplicate lines in the history.
HISTCONTROL=ignoredups:ignorespace
## append to the history file, don't overwrite it
shopt -s histappend

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

PS1='\[\033[07;36m\] \$ \[\033[01;33m\]\w\[\033[00m\] '

# shellcheck source=/dev/null
[[ -f ~/.bash_wsl ]] && . ~/.bash_wsl

# shellcheck source=/dev/null
[[ -f ~/.bash_msys2 ]] && . ~/.bash_msys2

# shellcheck source=/dev/null
[[ -f ~/.bash_aliases ]] && . ~/.bash_aliases

/bin/which say_todo.sh > /dev/null 2>&1 && say_todo.sh

# # run to Hyprland in and only in tty 1
# if [ -z "${DISPLAY}" ] && [ "${XDG_VTNR}" -eq 1 ]; then
#     exec Hyprland
# fi
